development:
  adapter: postgresql
  encoding: unicode
  database: url_shortner_dev
  pool: 5
  username: vipul
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: url_shortner_test
  pool: 5
  username: vipul
  password: