Rails.application.routes.draw do
  require 'sidekiq/web'  
  mount Sidekiq::Web, :at => '/sidekiq'
  get 'search' => 'elastic_search#search'
  get 'domain_prefix/domain_form'
  get 'domain_prefix/create_domain' =>'domain_prefix#create_domain'
  get 'users/login'
  get 'users/signup'
  get 'users/logout'
  get 'users/password_change'
  get 'home_page/index'
  root 'home_page#index'
  get 'urls/short_url_to_long_url'
  get 'urls/long_url_to_short_url'
  get 'urls/show'
  get 'urls/ShowShorten' => 'urls#convert_long_url_to_short_url'
  get'urls/ShowShort' => 'urls#retrieve_short_url_to_long_url'
  get '/short-url' => 'urls#api_get_short_url'
  post '/shorten-url' => 'urls#api_post_shorten_url'
  get '/users/CreateUser' => 'users#create_user'
  get '/users/Login' => 'users#check_login'
  get 'home_page/generate_report'
  get 'Search' => 'elastic_search#retrieve'
  get 'elastic_search/show'
  get 'home_page/Report' => 'home_page#generate_report'
end
