Rails.application.routes.draw do
  get 'search' => 'elastic_search#search'
  get 'domain_prefix/index'
  get 'users/login'
  get 'users/signup'
  get 'users/logout'
  get 'users/password_change'
  get 'home/index'
  root 'home#index'
  get 'urls/short_url_to_long_url'
  get 'urls/long_url_to_short_url'
  get 'urls/show'
  post 'urls/ShowShorten' => 'urls#convert_long_url_to_short_url'
  post'urls/ShowShort' => 'urls#retrieve_short_url_to_long_url'
  get '/short-url' => 'urls#api_get_short_url'
  post '/shorten-url' => 'urls#api_post_shorten_url'

  post '/users/CreateUser' => 'users#create_user'
  post '/users/Login' => 'users#check_login'
  require 'sidekiq/web'  
mount Sidekiq::Web, :at => '/sidekiq'
get 'home/generate_report'
post 'Search' => 'elastic_search#retrieve'
get 'elastic_search/show'

end
